### ISSUE TITLE
NO PUBKEY

### ISSUE THREAD

**Issue by dpazz** [radxa-repo/bullseye#2]
'sudo apt update' gives the following error:
Error:9 https://radxa-repo.github.io/apt rockchip-bullseye InRelease                              
  Le seguenti firme non sono state verificate perché la chiave pubblica non è disponibile: NO_PUBKEY 883854C2D3D73467

The second line is in italian because of the localisation of the OS. I try to back translate it to english:     
  The following signatures weren't verifed because the public key isn't available: NO_PUBKEY 883854C2D3D73467

I omit to copy here the obvious warnigs emitted by  'sudo apt update' in consequence of the former error.

**Comment by RadxaYuntian** [comment]
How come you are using that archive? It was archived.
Can you show me the image that has this enabled? There shouldn't be any.
